# Generated by Django 4.1.4 on 2022-12-17 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculo', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('numero', models.IntegerField(blank=True, null=True, unique=True)),
                ('idveiculo', models.OneToOneField(db_column='idVeiculo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='veiculo.veiculo')),
                ('datasaida', models.DateField(db_column='dataSaida')),
                ('dataretorno', models.DateField(blank=True, db_column='dataRetorno', null=True)),
                ('datadevolucao', models.DateField(blank=True, db_column='dataDevolucao', null=True)),
                ('valorreserva', models.DecimalField(blank=True, db_column='valorReserva', decimal_places=2, max_digits=10, null=True)),
                ('multa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorpago', models.DecimalField(blank=True, db_column='valorPago', decimal_places=2, max_digits=10, null=True)),
                ('codigocliente', models.ForeignKey(db_column='codigoCliente', on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
            ],
            options={
                'db_table': 'contrato',
                'unique_together': {('idveiculo', 'codigocliente', 'datasaida')},
            },
        ),
    ]
