# Generated by Django 4.1.4 on 2022-12-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=8, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=11, null=True)),
                ('cnpj', models.CharField(blank=True, db_column='CNPJ', max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
