# Generated by Django 4.1.4 on 2022-12-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
