# Generated by Django 4.1.4 on 2022-12-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.AutoField(db_column='codigo', primary_key=True, serialize=False, unique=True),
        ),
    ]
