# Generated by Django 4.1.4 on 2022-12-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('populacao', models.IntegerField(blank=True, null=True)),
                ('anofundacao', models.IntegerField(blank=True, db_column='anoFundacao', null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'cidade',
            },
        ),
    ]
