# Generated by Django 4.1.4 on 2022-12-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
