# Generated by Django 4.1.4 on 2022-12-17 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, db_column='CEP', max_length=8, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('idcidade', models.ForeignKey(blank=True, db_column='idCidade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cidade.cidade')),
            ],
            options={
                'db_table': 'filial',
            },
        ),
    ]
