# Generated by Django 4.1.4 on 2022-12-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('codigocliente', models.IntegerField(db_column='codigoCliente', primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'telefone',
                'unique_together': {('codigocliente', 'numero')},
            },
        ),
    ]
