# Generated by Django 4.1.4 on 2022-12-17 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=7, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('numportas', models.IntegerField(blank=True, db_column='numPortas', null=True)),
                ('arcondicionado', models.CharField(blank=True, db_column='arCondicionado', max_length=1, null=True)),
                ('vencimentoseguro', models.DateField(blank=True, db_column='vencimentoSeguro', null=True)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('valordiaria', models.DecimalField(blank=True, db_column='valorDiaria', decimal_places=2, max_digits=5, null=True)),
                ('codfilial', models.ForeignKey(blank=True, db_column='codFilial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filial.filial')),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
    ]
